---
version: "3"
services:
  casproxy:
    build: .
    environment: 
      - NODE_ENV=development
      - VALIDUSER=evs767
      - DESTPORT=8080
      - DEST=sid_desktop
    ports:
      - "443:443"
    links:
      - sid_desktop
    depends_on:
      - sid_desktop
  sid_desktop:
    image: hmdc/sid-desktop:latest
    ports:
      - "8080"
